- name: Deploy Docker Compose stacks
  when: docker_compose_stacks is defined and docker_compose_stacks | length > 0
  block:
    - name: Ensure directory for Docker Compose stacks exists
      ansible.builtin.file:
        path: "{{ item.dest | default(ansible_env.HOME + '/' + item.name) }}"
        state: directory
        mode: '0755'
      with_items: "{{ docker_compose_stacks }}"

    - name: Copy Docker Compose files
      ansible.builtin.template:
        src: "{{ (item.src | default(playbook_dir + '/stacks/' + item.name )) + '/docker-compose.yml.j2' }}"
        dest: "{{ (item.dest | default(ansible_env.HOME + '/' + item.name)) + '/docker-compose.yml' }}"
      with_items: "{{ docker_compose_stacks }}"

    - name: Synchronize Configs
      synchronize:
        src: "{{ (item.src | default(playbook_dir + '/stacks/' + item.name )) + '/' }}"
        dest: "{{ item.dest | default(ansible_env.HOME + '/' + item.name) }}"
        rsync_opts:
          - "--no-motd"
          - "--exclude={{ item.exclude | default('*.j2') }}"
      with_items: "{{ docker_compose_stacks }}"

    - name: Deploy Docker Compose stack
      community.docker.docker_compose_v2:
        project_src: "{{ item.dest | default(ansible_env.HOME + '/' + item.name) }}"
        pull: "{{ item.pull | default('missing') }}"
        files: "docker-compose.yml"
        remove_orphans: "{{ item.remove_orphans | default('true') }}"
        state: present
      with_items: "{{ docker_compose_stacks }}"
